#!/bin/sh

DOCKER_TAG=${DOCKER_TAG:=aliroot-installed}

docker run --rm -it \
        -v $HOME/.alice:$HOME/.alice \
        -v $HOME/.globus:$HOME/.globus \
        -v $HOME/development/physics/pipi_analysis:$HOME/analysis \
	-v /alice:/alice  \
        ${DOCKER_TAG} \
        /bin/bash



##!/usr/bin/env python3.5
##
## runme... setup and execute docker files
#
#
#from sh import docker
#
#



